name: Build KDE Localization Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gettext build-essential

    - name: List files in repository
      run: |
        echo "Listing files at root level:"
        ls -la
        echo "Listing files in messages directory:"
        ls -la messages

    - name: Compile translations
      run: |
        mkdir -p build
        cd messages
        for po_file in *.po; do
          echo "Processing $po_file"
          mo_file="../build/$(basename "$po_file" .po).mo"
          msgfmt "$po_file" -o "$mo_file"
        done

    - name: Package localization
      run: |
        cd build
        tar -czf localization-package.tar.gz *.mo
        mkdir -p $HOME/artifacts
        mv localization-package.tar.gz $HOME/artifacts/
      
    - name: Upload localization package
      uses: actions/upload-artifact@v3
      with:
        name: localization-package
        path: $HOME/artifacts/localization-package.tar.gz
