name: Build KDE Localization Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gettext build-essential

    - name: Compile translations
      run: |
        # Replace with the path to your messages folder and build script
        mkdir -p build
        cd messages
        for po_file in *.po; do
          mo_file="../build/$(basename "$po_file" .po).mo"
          msgfmt "$po_file" -o "$mo_file"
        done

    - name: Package localization
      run: |
        # Replace with the path to your build script or packaging command
        cd build
        tar -czf kde-el.tar.gz *.mo
        # Optionally, upload the package as an artifact
        mkdir -p $HOME/artifacts
        mv kde-el.tar.gz $HOME/artifacts/
      
    - name: Upload localization package
      uses: actions/upload-artifact@v3
      with:
        name: kde-el
        path: $HOME/artifacts/kde-el.tar.gz
